In [1]:
import requests
import io
import sys
import json
import sqlite3
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential, load_model
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from tensorflow.keras import backend as K
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.regularizers import l2

In [6]:


url = "https://api.themoviedb.org/3/genre/movie/list?language=en"

headers = {
    "accept": "application/json",
    "Authorization": "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIxZjlmNjAwMzY4MzMzODNkNGIwYjNhNzJiODA3MzdjNCIsInN1YiI6IjY0NzA5YmE4YzVhZGE1MDBkZWU2ZTMxMiIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.Em7Y9fSW94J91rbuKFjDWxmpWaQzTitxRKNdQ5Lh2Eo"
}

response = requests.get(url, headers=headers)
data = json.loads(response.text)

# Create the desired dictionary
genre_dict = {genre["id"]: genre["name"] for genre in data["genres"]}
genre_dict = {key: genre_dict[key] for key in sorted(genre_dict.keys())}
print(genre_dict)
genere_text = ', '.join([f'{genre.replace(" ", "_")} BOOL DEFAULT 0' for genre in genre_dict.values()])

{12: 'Adventure', 14: 'Fantasy', 16: 'Animation', 18: 'Drama', 27: 'Horror', 28: 'Action', 35: 'Comedy', 36: 'History', 37: 'Western', 53: 'Thriller', 80: 'Crime', 99: 'Documentary', 878: 'Science Fiction', 9648: 'Mystery', 10402: 'Music', 10749: 'Romance', 10751: 'Family', 10752: 'War', 10770: 'TV Movie'}


In [19]:
# Change the default encoding for stdout to utf-8
# sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')
page = 1


def get_movies(pages):
    dict_movies = {}
    
    for i in range(1,pages+1):
        url = f"https://api.themoviedb.org/3/movie/popular?language=en-US&page={i}"

        headers = {
            "accept": "application/json",
            "Authorization": "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIxZjlmNjAwMzY4MzMzODNkNGIwYjNhNzJiODA3MzdjNCIsInN1YiI6IjY0NzA5YmE4YzVhZGE1MDBkZWU2ZTMxMiIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.Em7Y9fSW94J91rbuKFjDWxmpWaQzTitxRKNdQ5Lh2Eo"
        }

        response = requests.get(url, headers=headers)

        # print(response.text)
        # Parse the JSON string into a Python dictionary
        data = json.loads(response.text)

        # Create the desired dictionary
        result_dict = {movie["id"]: [movie["title"], movie["genre_ids"], movie["poster_path"]] for movie in data["results"]}
        dict_movies = dict_movies | result_dict
        # Print the result dictionary
    return dict_movies


dict_movies = get_movies(500)
dict_movies = {k: dict_movies[k] for k in sorted(dict_movies)}
print(len(dict_movies))

9998


In [20]:
con = sqlite3.connect('C:/Users/yassi/Desktop/EI/My/MovieScope/backend/database.sqlite3')
cur = con.cursor()
cur.execute('''
                 CREATE TABLE IF NOT EXISTS Movies (
                     id INT PRIMARY KEY,
                     Title TEXT NOT NULL,
                     Genre TEXT NOT NULL,
                     Cover TEXT
                 )
                 ''')

cur.execute('''
                 CREATE TABLE IF NOT EXISTS Rating (
                     id_user INT,
                     id_movie INT,
                     rating float,
                     PRIMARY KEY (id_user, id_movie)
                 )
                 ''')

In [21]:

for key in dict_movies:
    cur.execute('''
        INSERT OR IGNORE INTO Movies (id, Title, Genre, Cover)
        VALUES (?, ?, ?, ?)
    ''', (key, dict_movies[key][0], json.dumps(dict_movies[key][1]), dict_movies[key][2]))

con.commit()
con.close()

In [3]:
con.commit()
con.close()

NameError: name 'con' is not defined

In [8]:
con = sqlite3.connect('C:/Users/yassi/Desktop/EI/My/MovieScope/backend/database.sqlite3')
cur = con.cursor()


# Create the table with the correct column definitions
cur.execute(f'''
    CREATE TABLE IF NOT EXISTS Users (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        email TEXT NOT NULL,
        password TEXT NOT NULL,
        {genere_text}
    )
''')
con.commit()
con.close()

In [33]:
genre_dict #19 element

{12: 'Adventure',
 14: 'Fantasy',
 16: 'Animation',
 18: 'Drama',
 27: 'Horror',
 28: 'Action',
 35: 'Comedy',
 36: 'History',
 37: 'Western',
 53: 'Thriller',
 80: 'Crime',
 99: 'Documentary',
 878: 'Science Fiction',
 9648: 'Mystery',
 10402: 'Music',
 10749: 'Romance',
 10751: 'Family',
 10752: 'War',
 10770: 'TV Movie'}

In [77]:
import sqlite3
import numpy as np
import random

# Connect to the SQLite database
conn = sqlite3.connect('C:/Users/yassi/Desktop/EI/My/MovieScope/backend/database.sqlite3')
cur = conn.cursor()

# Get the first 40 movie IDs from the Movies table in the order they appear
cur.execute('SELECT id FROM Movies LIMIT 60')
movie_ids = [row[0] for row in cur.fetchall()]

# Generate random ratings for each movie ID
user_id = 2
random_ratings = {movie_id: round(random.uniform(1.0, 5.0), 1) for movie_id in movie_ids}

# Insert the random ratings into the Rating table
for movie_id, rating in random_ratings.items():
    cur.execute('''
        INSERT OR REPLACE INTO Rating (id_user, id_movie, rating)
        VALUES (?, ?, ?)
    ''', (user_id, movie_id, rating))

# Commit the changes and close the database connection
conn.commit()
conn.close()

print("Random ratings generated and inserted for user_id 2")


Random ratings generated and inserted for user_id 2


In [35]:
import sqlite3
import numpy as np

# Connect to the SQLite database
conn = sqlite3.connect('C:/Users/yassi/Desktop/EI/My/MovieScope/backend/database.sqlite3')
cur = conn.cursor()

# Get the list of movie IDs from the Movies table in the order they appear
cur.execute('SELECT id FROM Movies')
movie_ids = [row[0] for row in cur.fetchall()]

# Get the total number of movies
num_movies = len(movie_ids)

# Initialize a vector of zeros with the length of the total number of movies
user_vector = np.zeros(num_movies)

# Get the ratings for user with id_user = 1
cur.execute('SELECT id_movie, rating FROM Rating WHERE id_user = 1')
user_ratings = cur.fetchall()

# Create a dictionary for quick lookup of ratings
rating_dict = {movie_id: rating for movie_id, rating in user_ratings}

# Populate the user_vector with the ratings based on the order of movie_ids
for idx, movie_id in enumerate(movie_ids):
    if movie_id in rating_dict:
        user_vector[idx] = rating_dict[movie_id]

# Close the database connection
conn.close()

# Print the length of the user_vector to verify
print(len(user_vector))

# Print the user_vector to verify the ratings
print(user_vector)


9998
[2.6 1.4 4.3 ... 0.  0.  0. ]


In [38]:
import sqlite3
import numpy as np
import random
import json

# Genre dictionary
genres = {
    12: 'Adventure',
    14: 'Fantasy',
    16: 'Animation',
    18: 'Drama',
    27: 'Horror',
    28: 'Action',
    35: 'Comedy',
    36: 'History',
    37: 'Western',
    53: 'Thriller',
    80: 'Crime',
    99: 'Documentary',
    878: 'Science_fiction',
    9648: 'Mystery',
    10402: 'Music',
    10749: 'Romance',
    10751: 'Family',
    10752: 'War',
    10770: 'TV_movie'
}

# Connect to the SQLite database
conn = sqlite3.connect('C:/Users/yassi/Desktop/EI/My/MovieScope/backend/database.sqlite3')
cur = conn.cursor()

# Get the ratings and genres for movies rated by user_id 1
cur.execute('''
    SELECT m.Genre, r.rating
    FROM Movies m
    JOIN Rating r ON m.id = r.id_movie
    WHERE r.id_user = 1
''')
user_ratings = cur.fetchall()

# Initialize a dictionary to store total ratings and counts for each genre
genre_ratings = {genre: {'total_rating': 0, 'count': 0} for genre in genres.values()}

# Calculate total ratings and counts for each genre
for genre_list, rating in user_ratings:
    genre_ids = json.loads(genre_list)  # Convert JSON string back to list of genre ids
    for genre_id in genre_ids:
        genre_name = genres.get(genre_id)
        if genre_name:
            genre_ratings[genre_name]['total_rating'] += rating
            genre_ratings[genre_name]['count'] += 1

# Calculate average ratings for each genre
average_genre_ratings = {genre: (info['total_rating'] / info['count'] if info['count'] > 0 else 0)
                         for genre, info in genre_ratings.items()}

# Update the Users table with the average ratings for each genre for user_id 1
update_query = '''
    UPDATE Users
    SET Adventure = ?,
        Fantasy = ?,
        Animation = ?,
        Drama = ?,
        Horror = ?,
        Action = ?,
        Comedy = ?,
        History = ?,
        Western = ?,
        Thriller = ?,
        Crime = ?,
        Documentary = ?,
        Science_fiction = ?,
        Mystery = ?,
        Music = ?,
        Romance = ?,
        Family = ?,
        War = ?,
        TV_movie = ?
    WHERE id = 1
'''

cur.execute(update_query, [
    average_genre_ratings['Adventure'],
    average_genre_ratings['Fantasy'],
    average_genre_ratings['Animation'],
    average_genre_ratings['Drama'],
    average_genre_ratings['Horror'],
    average_genre_ratings['Action'],
    average_genre_ratings['Comedy'],
    average_genre_ratings['History'],
    average_genre_ratings['Western'],
    average_genre_ratings['Thriller'],
    average_genre_ratings['Crime'],
    average_genre_ratings['Documentary'],
    average_genre_ratings['Science_fiction'],
    average_genre_ratings['Mystery'],
    average_genre_ratings['Music'],
    average_genre_ratings['Romance'],
    average_genre_ratings['Family'],
    average_genre_ratings['War'],
    average_genre_ratings['TV_movie']
])

# Commit the changes and close the database connection
conn.commit()
conn.close()

print("User genre ratings updated for user_id 1")


User genre ratings updated for user_id 1


In [41]:
# Connect to the SQLite database
conn = sqlite3.connect('C:/Users/yassi/Desktop/EI/My/MovieScope/backend/database.sqlite3')
cur = conn.cursor()

# Get the movie data
cur.execute('SELECT Genre FROM Movies')
movies = [json.loads(row[0]) for row in cur.fetchall()]

# Close the database connection
conn.close()

# Initialize the matrix
num_movies = len(movies)
num_genres = len(genres)
movie_train = np.zeros((num_movies, num_genres), dtype=int)

# Create a mapping from genre ID to column index
genre_to_index = {genre_id: index for index, genre_id in enumerate(genres.keys())}

# Populate the matrix
for i, movie_genres in enumerate(movies):
    for genre_id in movie_genres:
        if genre_id in genre_to_index:
            movie_train[i, genre_to_index[genre_id]] = 1
movie_train = np.array(movie_train)
# Print the genre matrix
print(movie_train)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]]


In [49]:
conn = sqlite3.connect('C:/Users/yassi/Desktop/EI/My/MovieScope/backend/database.sqlite3')
cur = conn.cursor()
cur.execute('SELECT * FROM Users WHERE id=1')
user_data = cur.fetchone()
def replicate_list(input_list, n):
    return [input_list] * n
user_data = replicate_list(user_data[3:], num_movies)
user_train = np.array(user_data)
print(user_train)
conn.close()

[[2.8        2.22       1.43333333 ... 1.35       4.9        0.        ]
 [2.8        2.22       1.43333333 ... 1.35       4.9        0.        ]
 [2.8        2.22       1.43333333 ... 1.35       4.9        0.        ]
 ...
 [2.8        2.22       1.43333333 ... 1.35       4.9        0.        ]
 [2.8        2.22       1.43333333 ... 1.35       4.9        0.        ]
 [2.8        2.22       1.43333333 ... 1.35       4.9        0.        ]]


In [74]:
import tensorflow
num_user_features = 19
num_item_features = 19
y_train = user_vector.reshape(-1, 1)
movie_train_normal= movie_train / (np.sum(movie_train, keepdims=True)+10e-4)
user_NN = Sequential([
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dense(32, activation='relu'),
    tf.keras.layers.Dense(19, activation='linear'),
    
    
])

movie_NN = Sequential([
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dense(32, activation='relu'),
    tf.keras.layers.Dense(19, activation='linear'),
    
    
])

# Create the user input and point to the base network
input_user = tf.keras.layers.Input(shape=(num_user_features,))
vu = user_NN(input_user)
vu = tf.linalg.l2_normalize(vu, axis=1)

# Create the item input and point to the base network
input_item = tf.keras.layers.Input(shape=(num_item_features,))
vm = movie_NN(input_item)
vm = tf.linalg.l2_normalize(vm, axis=1)

# Measure the similarity of the two vector outputs
output = tf.keras.layers.Dot(axes=1)([vu, vm])

# Specify the inputs and output of the model
model = tensorflow.keras.models.Model([input_user, input_item], output)

# Specify the cost function
cost_fn = tf.keras.losses.MeanSquaredError()

# Compile the model
model.compile(optimizer='adam', loss=cost_fn)

tf.random.set_seed(1)
cost_fn = tf.keras.losses.MeanSquaredError()
opt = tf.keras.optimizers.Adam(learning_rate=0.01)
model.compile(optimizer=opt,
              loss=cost_fn)

# Display the model summary
model.fit([user_train, movie_train_normal], y_train, epochs=30)


Epoch 1/30
313/313 [==============================] - 2s 2ms/step - loss: 0.0370
Epoch 2/30
313/313 [==============================] - 1s 2ms/step - loss: 0.0357
Epoch 3/30
313/313 [==============================] - 1s 2ms/step - loss: 0.0356
Epoch 4/30
313/313 [==============================] - 1s 2ms/step - loss: 0.0355
Epoch 5/30
313/313 [==============================] - 1s 2ms/step - loss: 0.0354
Epoch 6/30
313/313 [==============================] - 1s 2ms/step - loss: 0.0353
Epoch 7/30
313/313 [==============================] - 1s 2ms/step - loss: 0.0353
Epoch 8/30
313/313 [==============================] - 1s 2ms/step - loss: 0.0354
Epoch 9/30
313/313 [==============================] - 1s 2ms/step - loss: 0.0353
Epoch 10/30
313/313 [==============================] - 1s 2ms/step - loss: 0.0353
Epoch 11/30
313/313 [==============================] - 1s 3ms/step - loss: 0.0354
Epoch 12/30
313/313 [==============================] - 1s 3ms/step - loss: 0.0353
Epoch 13/30
313/313 [====

In [68]:
conn = sqlite3.connect('C:/Users/yassi/Desktop/EI/My/MovieScope/backend/database.sqlite3')
cur = conn.cursor()
cur.execute('SELECT * FROM Movies')
movies_list = cur.fetchall()
print(movies_list[0])
cur.close()

(5, 'Four Rooms', '[35]', '/75aHn1NOYXh4M7L5shoeQ6NGykP.jpg')


In [83]:
import ast
conn = sqlite3.connect('C:/Users/yassi/Desktop/EI/My/MovieScope/backend/database.sqlite3')
cur = conn.cursor()
# Predict scores for all movies
y_predict = model.predict([user_train, movie_train_normal])
y_predict = np.squeeze(y_predict)
def get_top_n_indexes(arr, n):
    # Get the indexes that would sort the array in decreasing order
    sorted_indexes = np.argsort(arr)[::-1]
    # Select the first n indexes
    top_n_indexes = sorted_indexes[:n]
    return top_n_indexes

cur.execute('SELECT id FROM Movies')
all_movie_ids = [row[0] for row in cur.fetchall()]
cur.execute(f'SELECT id_movie FROM Rating WHERE id_user = 1')
id_movies_watched = cur.fetchall()
id_movies_watched = [ids[0] for ids in id_movies_watched]
print(id_movies_watched)
n=50
indexes =  get_top_n_indexes(y_predict, len(y_predict))
print(indexes)
unwatched_movie_indexes = [i for i in indexes if all_movie_ids[i] not in id_movies_watched][:50]
k = 0
for i in unwatched_movie_indexes:
    k+=1
    genres_list = '/'.join([genres[j] for j in ast.literal_eval(movies_list[i][2])])
    print(f'{k} : Movie ID : {movies_list[i][0]}, Title : {movies_list[i][1]} with genres {genres_list} has score {y_predict[i]} \n')
# print(movies)


313/313 [==============================] - 1s 2ms/step
[5, 6, 11, 12, 13, 14, 15, 16, 18, 19, 22, 24, 25, 27, 28, 33, 35, 38, 55, 58, 59, 62, 63, 64, 65, 66, 68, 69, 70, 71, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82]
[3381 5734  786 ... 3240 2073 7106]
1 : Movie ID : 17835, Title : Threads with genres War/Drama/Science_fiction has score 0.006773737724870443 

2 : Movie ID : 281338, Title : War for the Planet of the Apes with genres Drama/Science_fiction/War has score 0.006773737724870443 

3 : Movie ID : 1880, Title : Red Dawn with genres Action/Thriller/War/Drama/Science_fiction has score 0.006773635745048523 

4 : Movie ID : 46738, Title : Incendies with genres Drama/War/Mystery has score 0.0067735216580331326 

5 : Movie ID : 25388, Title : March or Die with genres Drama/Adventure/War has score 0.006773495581001043 

6 : Movie ID : 17339, Title : Force 10 from Navarone with genres Drama/Adventure/War has score 0.006773495581001043 

7 : Movie ID : 8619, Title : Master and Commander: Th